### ISSUE TITLE
调度策略交流

### ISSUE THREAD

**Issue by Charlie17Li** [ZhaoKe1024/IntelligentAlgorithmScheduler#1]
老哥你好，目前我也在搞调度策略，可以加个好友吗， charlie1213800@gmail.com

**Comment by ZhaoKe1024** [comment]
> 老哥你好，目前我也在搞调度策略，可以加个好友吗， [charlie1213800@gmail.com](mailto:charlie1213800@gmail.com)

可以呀，我常用邮箱 mathcszk271828@foxmail.com

**Comment by Charlie17Li** [comment]
好的，我加你
